History
LucaNeocoast/neotracker pull request #6
Opened 2022-03-24 20:11 UTC by LucaNeocoast

![Captura de pantalla 2022-03-24 a la(s) 17 07 29](https://user-images.githubusercontent.com/83365842/160001573-eea0f840-d2fa-4da8-b756-7a55da860bbd.png)
![Captura de pantalla 2022-03-24 a la(s) 17 07 24](https://user-images.githubusercontent.com/83365842/160001579-d3803bdb-d67f-473d-af33-7a91c741a6ad.png)

2022-03-30 18:49 UTC, gonzasismo commented on src/api/Axios/axios.js
> +  return api.delete(
```suggestion
  } = getUserData();
  
  return api.delete(
```

2022-03-30 18:49 UTC, gonzasismo commented on src/api/Axios/axios.js
> +  return (api.get(
Mismo comentario que aca. No es necesario el `(`.

2022-03-30 18:50 UTC, gonzasismo commented on src/components/Day/index.jsx
> +import './index.scss';
```suggestion
import React from 'react';
import { format } from 'date-fns';
import PropTypes from 'prop-types';

import ProjectsLists from 'Components/ProjectsLists';

import './index.scss';
```

2022-03-30 18:51 UTC, gonzasismo commented on src/components/Day/index.scss
> +      background-color:$line_color;
Ups
```suggestion
      background-color: $line_color;
```

2022-03-30 18:53 UTC, gonzasismo commented on src/components/DaysLists/index.jsx
> +};
Upss. Quedó un `console.log`, y también no hay necesidad del `return`, ya que la función puede hacer un return implicito.

```suggestion
const DaysLists = ({ days }) => (
    <>
      {
        days.map(({
          date, projects, tracked_time,
        }) => (
          <Day
            date={date}
            projects={projects}
            trackedTime={tracked_time}
          />
        ))
      }
    </>
  );
```

2022-03-30 18:54 UTC, gonzasismo commented on src/components/Entries/index.jsx
> +import PropTypes from 'prop-types';
```suggestion
import React, { useState, useEffect } from 'react';
import { format, differenceInMinutes } from 'date-fns';
import { minutesToHours } from 'date-fns/esm';
import PropTypes from 'prop-types';
```

2022-03-30 18:55 UTC, gonzasismo commented on src/components/EntriesLists/index.jsx
> +};
Mismo comentario aca que en la componente anterior. Console.log y return implicito.

2022-03-30 18:55 UTC, gonzasismo commented on src/components/Project/index.jsx
> +  console.log(tags);
Ups

2022-03-30 18:55 UTC, gonzasismo commented on src/components/Project/index.jsx
> +  tags, color, name, trackedTime,
```suggestion
  tags, 
  color, 
  name,
  trackedTime,
```

2022-03-30 18:56 UTC, gonzasismo commented on src/components/Project/index.jsx
> +  };
Que opinas de hacer algo de este estilo?
```suggestion
  const opening = () => setOpen(!open);
```

2022-03-30 18:59 UTC, gonzasismo commented on src/components/Project/index.jsx
> +            {open ? (<ArrowDown onClick={opening} />) : <ArrowRigth onClick={opening} />}
Esto no esta mal, pero los `()` no son necesarios.
```suggestion
            {open ? <ArrowDown onClick={opening} /> : <ArrowRigth onClick={opening} />}
```

2022-03-30 19:00 UTC, gonzasismo commented on src/components/Project/index.scss
> +    background-color:$line_color;
```suggestion
    background-color: $line_color;
```

2022-03-30 19:00 UTC, gonzasismo commented on src/components/ProjectsLists/index.jsx
> +        tags, project, tracked_time,
```suggestion
        tags, 
        project, 
        tracked_time,
```

2022-03-30 19:01 UTC, gonzasismo commented on src/components/Sidebar/index.jsx
> +  return (
```suggestion
  ];
  
  return (
```

2022-03-30 19:01 UTC, gonzasismo commented on src/components/Sidebar/index.jsx
> +          <button type="submit" className={item.path === location.pathname ? 'sidebar__button active' : 'sidebar__button inactive'} onClick={() => navigate(item.path)}>
```suggestion
        {
          items.map((item) => (
            <button type="submit" className={item.path === location.pathname ? 'sidebar__button active' : 'sidebar__button inactive'} onClick={() => navigate(item.path)}>
```

2022-03-30 19:01 UTC, gonzasismo commented on src/components/Sidebar/index.jsx
> +  const clear = () => {
```suggestion
  };
  
  const clear = () => {
```

2022-03-30 19:03 UTC, gonzasismo commented on src/components/Sidebar/index.jsx
> +      localStorage.removeItem('accessToken');
Que opinas de mover esta logica en `logOut` para `'Axios/axios'` ?>

2022-03-30 19:04 UTC, gonzasismo commented on src/components/Sidebar/index.jsx
> +          <button type="submit" className={item.path === location.pathname ? 'sidebar__button active' : 'sidebar__button inactive'} onClick={() => navigate(item.path)}>
```suggestion
          <button 
            type="submit" 
            className={item.path === location.pathname ? 'sidebar__button active' : 'sidebar__button inactive'} 
            onClick={() => navigate(item.path)}
          >
```

2022-03-30 19:04 UTC, gonzasismo commented on src/components/Sidebar/index.jsx
> +      </div>
Esto esta bien, tambien podria ser un boton en vez de un div.

2022-03-30 19:04 UTC, gonzasismo commented on src/components/Sidebar/index.scss
> +
Linea extra
```suggestion
```

2022-03-30 19:05 UTC, gonzasismo commented on src/components/Sidebar/index.scss
> +
Ups
```suggestion

```

2022-03-30 19:06 UTC, gonzasismo commented on src/components/Tag/index.jsx
> +            {open ? (<ArrowDown onClick={opening} />) : <ArrowRigth onClick={opening} />}
Mismo comentario con los `()`.

2022-03-30 19:06 UTC, gonzasismo commented on src/components/Tag/index.jsx
> +      {open && <><EntriesLists entries={entries} /><div className="tag__empty" /></>}
```suggestion
      {
        open &&  (
          <>
            <EntriesLists entries={entries} />
            <div className="tag__empty" />
          </>
        )
      }
```

2022-03-30 19:08 UTC, gonzasismo commented on src/containers/Reports/index.scss
> +    }
Creo que habías borrado esta classname anteriormente en el index.
```suggestion
```

2022-03-30 19:09 UTC, gonzasismo commented on src/containers/SignIn/index.jsx
> +      localStorage.setItem('client', response.headers.client);
Mismo comentario, de mover esta logica al signIn en `Axios/axios`.

2022-03-30 19:16 UTC, gonzasismo commented on src/containers/Timer/index.jsx
> +  return (
```suggestion
  }, []);
  
  return (
```

2022-03-30 19:16 UTC, gonzasismo commented on src/containers/Timer/index.jsx
> +          {!isFetchingHistory ? <DaysLists className="prueba" days={history} /> : <div />}
className="prueba" 👀

2022-03-30 19:16 UTC, gonzasismo reviewed
Gran trabajo!

Deje comentarios.

2022-04-05 18:00 UTC, gonzasismo commented on src/components/Day/index.scss
> +  &__container{
```suggestion
  &__container {
```

2022-04-05 18:00 UTC, gonzasismo commented on src/components/Day/index.scss
> +  &__container{
```suggestion
  &__container {
```

2022-04-05 18:01 UTC, gonzasismo commented on src/components/Entries/index.jsx
> +  const [diference, setDiference] = useState('');
```suggestion
  const [difference, setDifference] = useState('');
```

2022-04-05 18:01 UTC, gonzasismo commented on src/components/Entries/index.jsx
> +    setDiference(differenceInMinutes(new Date(finishDate), new Date(initialDate)));
```suggestion
    setDifference(differenceInMinutes(new Date(finishDate), new Date(initialDate)));
```

2022-04-05 18:01 UTC, gonzasismo commented on src/components/Entries/index.jsx
> +        <div className="entries__container-total">{diference > 0 ? `${minutesToHours(diference)}:${minutes}` : '0:0'}</div>
```suggestion
        <div className="entries__container-total">{difference > 0 ? `${minutesToHours(difference)}:${minutes}` : '0:0'}</div>
```

2022-04-05 18:02 UTC, gonzasismo commented on src/components/Entries/index.jsx
> +  }, [diference]);
```suggestion
  }, [difference]);
```

2022-04-05 18:02 UTC, gonzasismo commented on src/components/EntriesLists/index.jsx
> +import PropTypes from 'prop-types';
```suggestion
import React from 'react';
import PropTypes from 'prop-types';

import Entries from 'Components/Entries';
```

2022-04-05 18:07 UTC, gonzasismo commented on src/components/Project/index.jsx
> +import { minutesToHours } from 'date-fns/esm';
Recorda el orden de los imports
```suggestion
import React, { useState, useEffect } from 'react';
import { minutesToHours } from 'date-fns/esm';
import PropTypes from 'prop-types';

import TagsList from 'Components/TagsList';

```

2022-04-05 18:09 UTC, gonzasismo commented on src/components/Project/index.scss
> +    &-box{
```suggestion
    &-box {
```

2022-04-05 18:09 UTC, gonzasismo commented on src/components/ProjectsLists/index.jsx
> +import PropTypes from 'prop-types';
```suggestion
/* eslint-disable camelcase */
import React from 'react';
import PropTypes from 'prop-types';

import Project from 'Components/Project';
```

2022-04-05 18:10 UTC, gonzasismo commented on src/components/Sidebar/index.jsx
> +          <button
```suggestion
        {
          items.map((item) => (
            <button
```

2022-04-05 18:10 UTC, gonzasismo commented on src/components/Sidebar/index.jsx
> +        ))}
```suggestion
        ))
      }
```

2022-04-05 18:11 UTC, gonzasismo commented on src/components/Sidebar/index.scss
> +
Ups
```suggestion
```

2022-04-05 18:11 UTC, gonzasismo commented on src/components/Sidebar/index.scss
> +
Ups
```suggestion
```

2022-04-05 18:11 UTC, gonzasismo commented on src/components/Sidebar/index.scss
> +
Ups
```suggestion
```

2022-04-05 18:11 UTC, gonzasismo commented on src/components/Sidebar/index.scss
> +
ups
```suggestion
```

2022-04-05 18:12 UTC, gonzasismo commented on src/components/Tag/index.jsx
> +import PropTypes from 'prop-types';
Mismo comentario aqui del orden de imports.

2022-04-05 18:12 UTC, gonzasismo commented on src/components/Tag/index.jsx
> +import { format, differenceInMinutes } from 'date-fns';
Y aca tambien.

2022-04-05 18:12 UTC, gonzasismo commented on src/components/Tag/index.jsx
> +import { minutesToHours } from 'date-fns/esm';
Y aca.

2022-04-05 18:12 UTC, gonzasismo commented on src/components/Tag/index.jsx
> +  const [diference, setDiference] = useState('');
`difference` : )

2022-04-05 18:13 UTC, gonzasismo commented on src/components/Tag/index.jsx
> +    </div>
```suggestion
      {
        open && (
          <>
            <EntriesLists entries={entries} />
            <div className="tag__empty" />
          </>
        )
      }
    </div>
```

2022-04-05 18:26 UTC, gonzasismo requested changes
Gran trabajo! Comentado

2022-04-05 19:47 UTC, gonzasismo commented on src/components/Sidebar/index.jsx
> +
Sacaria este enter
```suggestion
      <div className="sidebar__container">
```

2022-04-05 19:48 UTC, gonzasismo commented on src/components/Sidebar/index.jsx
> +              className={item.path === location.pathname ? 'sidebar__button active' : 'sidebar__button inactive'}
No tenes por que cambiarlo, pero siguiendo BEM podrias haber hecho algo asi tambien

```
className={item.path === location.pathname ? 'sidebar__button--active' : 'sidebar__button--inactive'}
```

Ya que si tuvieses otras clases `active` o `inactive` podrian mezclarse.

2022-04-05 19:49 UTC, gonzasismo approved these changes
💪🏿 💪🏿 

Deje algun comentario mas pero excelente!

2022-04-05 20:32 UTC, LucaNeocoast commented on src/components/Sidebar/index.jsx
> +              className={item.path === location.pathname ? 'sidebar__button active' : 'sidebar__button inactive'}
ahi me fallaba por algo en especifico, corte precisaba 2 clases separadas entre los botones y si estaban activos o inactivos

2022-04-06 17:28 UTC, merged